//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polarsoft.Diplomacy.Daide.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polarsoft.Diplomacy.Daide.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown OrderType: &apos;{0}&apos;..
        /// </summary>
        internal static string Basebot_Exception_UnknownOrderType {
            get {
                return ResourceManager.GetString("Basebot_Exception_UnknownOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUH message received: &apos;{0}&apos;..
        /// </summary>
        internal static string Basebot_Trace_HUHMessage {
            get {
                return ResourceManager.GetString("Basebot_Trace_HUHMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order &apos;{0}&apos;. No replacement sent..
        /// </summary>
        internal static string Basebot_Trace_InvalidOrderNotReplaced {
            get {
                return ResourceManager.GetString("Basebot_Trace_InvalidOrderNotReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order &apos;{0}&apos; replaced with &apos;{1}&apos;..
        /// </summary>
        internal static string Basebot_Trace_InvalidOrderReplaced {
            get {
                return ResourceManager.GetString("Basebot_Trace_InvalidOrderReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message rejected: &apos;{0}&apos;..
        /// </summary>
        internal static string Basebot_Trace_MessageRejected {
            get {
                return ResourceManager.GetString("Basebot_Trace_MessageRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN Message received: &apos;{0}&apos;..
        /// </summary>
        internal static string Basebot_Trace_PRNMessage {
            get {
                return ResourceManager.GetString("Basebot_Trace_PRNMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected first token in message: &apos;{0}&apos;.
        /// </summary>
        internal static string Basebot_Trace_UnexpectedFirstToken {
            get {
                return ResourceManager.GetString("Basebot_Trace_UnexpectedFirstToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected {0} message: &apos;{1}&apos;..
        /// </summary>
        internal static string Basebot_Trace_UnexpectedMessage {
            get {
                return ResourceManager.GetString("Basebot_Trace_UnexpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown first token. Bytes: {0}, {1}..
        /// </summary>
        internal static string BaseBot_Trace_UnknownFirstToken {
            get {
                return ResourceManager.GetString("BaseBot_Trace_UnknownFirstToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM timer popped..
        /// </summary>
        internal static string Connection_ErrorMessage_01 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM was not the first message sent by the client..
        /// </summary>
        internal static string Connection_ErrorMessage_02 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM indicated the wrong endian..
        /// </summary>
        internal static string Connection_ErrorMessage_03 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM had an incorrect magic number..
        /// </summary>
        internal static string Connection_ErrorMessage_04 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version incompatibility..
        /// </summary>
        internal static string Connection_ErrorMessage_05 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 1 IM sent..
        /// </summary>
        internal static string Connection_ErrorMessage_06 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM sent by server..
        /// </summary>
        internal static string Connection_ErrorMessage_07 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown message received..
        /// </summary>
        internal static string Connection_ErrorMessage_08 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message shorter than expected..
        /// </summary>
        internal static string Connection_ErrorMessage_09 {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM sent before RM..
        /// </summary>
        internal static string Connection_ErrorMessage_0A {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM was not the first message sent by the server..
        /// </summary>
        internal static string Connection_ErrorMessage_0B {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 1 RM sent..
        /// </summary>
        internal static string Connection_ErrorMessage_0C {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM sent by client..
        /// </summary>
        internal static string Connection_ErrorMessage_0D {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token in DM..
        /// </summary>
        internal static string Connection_ErrorMessage_0E {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error code: {0}, {1}..
        /// </summary>
        internal static string Connection_ErrorMessage_Unknown {
            get {
                return ResourceManager.GetString("Connection_ErrorMessage_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type of token for an RM: {0}..
        /// </summary>
        internal static string Connection_Exception_UnknownRMToken {
            get {
                return ResourceManager.GetString("Connection_Exception_UnknownRMToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding default powers and provinces..
        /// </summary>
        internal static string Connection_Trace_DefaultPowers {
            get {
                return ResourceManager.GetString("Connection_Trace_DefaultPowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message received from server: {0}..
        /// </summary>
        internal static string Connection_Trace_ErrorMessage {
            get {
                return ResourceManager.GetString("Connection_Trace_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final message received from server: {0}, {1}..
        /// </summary>
        internal static string Connection_Trace_FinalMessage {
            get {
                return ResourceManager.GetString("Connection_Trace_FinalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving message: {0}..
        /// </summary>
        internal static string Connection_Trace_MessageReceived {
            get {
                return ResourceManager.GetString("Connection_Trace_MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power: {0}..
        /// </summary>
        internal static string Connection_Trace_Power {
            get {
                return ResourceManager.GetString("Connection_Trace_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powers..
        /// </summary>
        internal static string Connection_Trace_Powers {
            get {
                return ResourceManager.GetString("Connection_Trace_Powers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding powers and provinces from RM..
        /// </summary>
        internal static string Connection_Trace_PowersFromRM {
            get {
                return ResourceManager.GetString("Connection_Trace_PowersFromRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province: {0} (Type: {1})..
        /// </summary>
        internal static string Connection_Trace_Province {
            get {
                return ResourceManager.GetString("Connection_Trace_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces..
        /// </summary>
        internal static string Connection_Trace_Provinces {
            get {
                return ResourceManager.GetString("Connection_Trace_Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message: {0}.
        /// </summary>
        internal static string Connection_Trace_SendMessage {
            get {
                return ResourceManager.GetString("Connection_Trace_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province: {0} (Type: {1}).
        /// </summary>
        internal static string Connector_Trace_Province {
            get {
                return ResourceManager.GetString("Connector_Trace_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add brackets yourself. Use MessageEnclosed or operator &apos;&amp;&apos; instead..
        /// </summary>
        internal static string Token_Exception_CannotAddBrackets {
            get {
                return ResourceManager.GetString("Token_Exception_CannotAddBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is not a number..
        /// </summary>
        internal static string Token_Exception_NotANumber {
            get {
                return ResourceManager.GetString("Token_Exception_NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add brackets yourself. Use MessageEnclosed or operator &apos;&amp;&apos; instead..
        /// </summary>
        internal static string TokenMessage_Exception_CannotAddBrackets {
            get {
                return ResourceManager.GetString("TokenMessage_Exception_CannotAddBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token array (Mismatch in parenthesis)..
        /// </summary>
        internal static string TokenMessage_Exception_ParenthesisMismatch {
            get {
                return ResourceManager.GetString("TokenMessage_Exception_ParenthesisMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown phase token: &apos;{0}&apos;..
        /// </summary>
        internal static string Util_Exception_UnknownPhase {
            get {
                return ResourceManager.GetString("Util_Exception_UnknownPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjacency From: &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string Util_Trace_NewAdjacency {
            get {
                return ResourceManager.GetString("Util_Trace_NewAdjacency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown coast type..
        /// </summary>
        internal static string Util_UnknownCoast {
            get {
                return ResourceManager.GetString("Util_UnknownCoast", resourceCulture);
            }
        }
    }
}
